import React from 'react';
import {
  ShieldCheck,
  BadgeCheck,
  Brain,
  Cpu,
} from 'lucide-react';

const features = [
  {
    title: 'RELIABILITY',
    icon: ShieldCheck,
    description: `JEW offers customer service as well as technical support from our inhouse licensed engineers. JEW provides customers detailed drawings of project together with a complete, fully itemized list of parts and accessories with written.`,
  },
  {
    title: 'QUALITY',
    icon: BadgeCheck,
    description: `All our parts are manufactured to the tolerances according to the practice followed by Metal Building Manufacturers Association. From the welds on our H Beams to our long-lasting paint finishes, JEW Quality Department only allows material dispatch.`,
  },
  {
    title: 'EXPERTISE',
    icon: Brain,
    description: `At JEW, we don't just sell steel, we design and engineer PEB in detail so the customer is assured that their order is in good hands. JEW staff is experienced in all types of Pre-engineered steel buildings whether it's an aircraft hangar or a two-story structure.`,
  },
  {
    title: 'JEW TECHNOLOGY',
    icon: Cpu,
    description: `CNC Cutting machine backed with plasma cutting source for cutting of steel plates taking directly input of drawing nested using Fastcam Nesting Software generated by special designing software.`,
  },
];

const RoofingFeatures = () => {
  return (
    <div className="bg-[#f5f6f1] max-w-7xl rounded-3xl px-16 mx-auto flex flex-col items-center  py-16  md:px-8">
      <h2 className="text-3xl md:text-4xl font-bold text-center text-orange-400 mb-12">
        WHY JEW
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {features.map((feature, index) => {
          const Icon = feature.icon;
          return (
            <div
              key={index}
              className="bg-white rounded-2xl p-6 shadow-sm transition-transform hover:scale-105"
            >
              <div className="flex items-center gap-3 mb-4">
                <Icon className="w-6 h-6 text-orange-400" />
                <h3 className="text-lg font-bold text-orange-400">{feature.title}</h3>
              </div>
              <p className="text-gray-700 whitespace-pre-line">{feature.description}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default RoofingFeatures;
